#!/usr/bin/python3

import argparse

try:    from argparse_tool import utils
except: argparse.Action.complete = lambda s, *_: s

argp = argparse.ArgumentParser(prog='argparse-tool-test',
    description='Test argument parser for shell completion')

argp.add_argument('--version',    action='version')
argp.add_argument('--file',       help='Complete a file').complete('file')
argp.add_argument('--directory',  help='Complete a directory').complete('directory')
argp.add_argument('--user',       help='Complete a user').complete('user')
argp.add_argument('--group',      help='Complete a group').complete('group')
argp.add_argument('--command',    help='Complete a command').complete('command')
argp.add_argument('--process',    help='Complete a process').complete('process')
argp.add_argument('--pid',        help='Complete a pid').complete('pid')
argp.add_argument('--signal',     help='Complete a signal').complete('signal')
argp.add_argument('--hostname',   help='Complete a hostname').complete('hostname')
argp.add_argument('--variable',   help='Complete a variable').complete('variable')
argp.add_argument('--service',    help='Complete a service').complete('service')
argp.add_argument('--choices',    help='Complete from choices', choices=(1,'two and a half',3))
argp.add_argument('--range',      help='Complete a range', type=int, choices=range(1,9,2))
argp.add_argument('-f', '--flag', help='A option flag', action='store_true') # TODO: remove me
argp.add_argument('--integer',    help='Option with integer', type=int)
argp.add_argument('-a', '-A', '--argument')
argp.add_argument('--single-quote-in-description',  help="Here is a single quote: '")
argp.add_argument('--double-quote-in-description',  help='Here is a double quote: "')
argp.add_argument('--special-chars-in-description', help='Here are some special chars: $(echo \'\\"`ls`")')
group = argp.add_mutually_exclusive_group()
group.add_argument('--exclusive-1', action='store_true')
group.add_argument('--exclusive-2', action='store_true')

subp = argp.add_subparsers(description='commands')

cmdp = subp.add_parser('dummy', help='Dummy command')

cmdp = subp.add_parser('positionals',  help='For testing positionals')
cmdp.add_argument('pos', help='First positional', choices=('first1', 'first2', 'first3'))
cmdp.add_argument('opt', help='Optional positional', choices=('optional1', 'optional2'), nargs='?')

cmdp = subp.add_parser('zsh', help='For testing zsh:')
cmdp.add_argument('--argument-with-colon-in-description', help='Colon follows:')

if __name__ == '__main__':
    argp.parse_args()
